---
- name: Install nginx
  yum: 
    name: nginx
    state: present
  become: yes

- name: Create site directory
  file:
    path: "{{ site_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Copy nginx configuration
  template: 
    src: app-defaults
    dest: /etc/nginx/app-defaults
  notify: restart nginx
  become: yes

- name: Copy nginx configuration
  template: 
    src: app.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: yes

- name: Insert firewalld rule for nginx
  firewalld:
    port: 80/tcp
    permanent: true 
    state: enabled
    immediate: yes
  become: yes

- name: Be sure nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes