---
- name: Install Postgres, Nginx, and PHP-FPM
  hosts: all
  remote_user: root

  roles:
    - common
    - postgres
    - nginx
    - docker

- name: Deploy app
  hosts: all
  remote_user: root

  tasks:
    - name: Create web directory
      file:
        path: "{{ site_dir }}/web"
        state: directory
        mode: '0755'

    - name: Copy app.php
      copy: 
        src: ./web/app.php
        dest: "{{ site_dir }}/web/app.php"

    - name: Run docker-compose
      shell:
        cmd: docker-compose up -d
        chdir: ~/app/
