---
- name: Delete content & directory
  file:
    state: absent
    path: "{{ build_dir }}/repo/"

- name: Copy remote repository
  git: 
    repo: https://github.com/muxx/sre-hello-world.git
    dest: "{{ build_dir }}/repo/"

- name: Create app directory
  file:
    path: "{{ site_dir }}/web"
    state: directory
    mode: '0755'
  become: yes

- name: Copy app.php to app directory
  copy:
    src: "{{ build_dir }}/repo/web/app.php"
    dest: "{{ site_dir }}/web/app.php"
    remote_src: yes
  become: yes

- name: Copy Dockerfile to work directory
  copy:
    src: "{{ build_dir }}/repo/docker/images/php/Dockerfile"
    dest: "{{ build_dir }}/Dockerfile"
    remote_src: yes

- name: Copy php.ini to work directory
  copy:
    src: "{{ build_dir }}/repo/docker/images/php/php.ini"
    dest: "{{ build_dir }}/php.ini"
    remote_src: yes

- name: Copy .env to work directory
  template:
    src: ".env"
    dest: "{{ build_dir }}/.env"

- name: Copy docker-compose.yml to work directory
  template:
    src: docker-compose.yml
    dest: "{{ build_dir }}/docker-compose.yml"

- name: Build and run container
  shell:
    cmd: /usr/local/bin/docker-compose up -d --build
    chdir: "{{ build_dir }}/"
  become: yes